### ISSUE TITLE
Erro treinamento Modelo Reconhecimento Facial

### ISSUE THREAD

**Issue by GuilhermeSola** [michelpf/fiap-ml-tec-proc-imagens-capstone#1]
Michel,

não estou conseguindo decifrar o motivo do erro abaixo ao tentar rodar o treinamento do modelo de reconhecimento facial do trabalho. Consegue me dar uma luz, por favor?

Algumas coisas que já chequei tentando descobrir o motivo do erro:
 - Os vetores 'training_data' e 'labels' estão com a mesma len (ambas > 0, onde 'training_data' contém as imagens salvas dos frames e 'labels' vetor de 0)
- As primeiras imagens salvas na pasta ficam vazias, já tentei rodar após deletar essas imagens e o erro persiste

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-55-9d95bc2acc6a> in <module>()
     18 # Treinamento do modelo
     19 model = cv2.face.LBPHFaceRecognizer_create()
---> 20 model.train(training_data, labels)
     21 
     22 print("Modelo treinado com sucesso.")

error: OpenCV(3.4.2) /opt/concourse/worker/volumes/live/9523d527-1b9e-48e0-7ed0-a36adde286f0/volume/opencv-suite_1535558719691/work/modules/core/src/matrix.cpp:235: error: (-215:Assertion failed) s >= 0 in function 'setSize'

**Comment by michelpf** [comment]
Coloque seu código num repositório para eu analisar o restante das instruções. Pode ser alguma coisa na etapa pré treinamento.

**Comment by GuilhermeSola** [comment]
Consegui encontrar o problema.

O primeiro valor do vetor de imagens de treinamento está None, por isso não está dando para treinar o modelo.
Consertei só eliminando esse None e reduzindo em 1 o len das labels.

Agora funciona.
