### ISSUE TITLE
Instalação Dlib

### ISSUE THREAD

**Issue by rafalfs** [michelpf/fiap-ml-tec-proc-imagens-capstone#2]
Oi Michel. 
Não estou conseguindo instalar o DLIB no anaconda. A instalação fica em execução e não termina nunca.
Tem alguma dica do que pode ser?

**Comment by michelpf** [comment]
Se seu OS for Mac, o procedimento é diferente, você precisa conferir os passos em https://www.learnopencv.com/install-dlib-on-macos/

Se for Windows, as vezes isso pode ocorrer. Já aconteceu comigo, e apesar de não ter a tela dizendo que foi concluído com sucesso, ao final quando criei um projeto novo importando a biblioteca funcionou normalmente.

Confira também se em seu computador o usuário está como administrador. A instalação do DLib instala diversos componentes do Windows que podem ser bloqueados pelas imagens de SOs de empresas. Na minha por exemplo acontece isso. Para contornar, procure executar o Console do Anaconda como Administrador.

**Comment by rafalfs** [comment]
Professor, meu SO é windows 10, consegui instalar baixando o compilador de c++ e utilizando o pip install. Pelo conda install não estava indo mesmo.
Obrigado!
Rafael.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by michelpf** [comment]
Excelente. 
Já que conseguiu resolver, vou fechar a Issue.
