### ISSUE TITLE
Erro: AttributeError: module 'cv2.cv2' has no attribute 'face'

### ISSUE THREAD

**Issue by henriquebraga-luizalabs** [michelpf/fiap-ml-tec-proc-imagens-capstone#3]
Quando tento executar esse trecho de código:

```python
data_path = 'imagens/'

onlyfiles = [f for f in listdir(data_path) if isfile(join(data_path, f))]
training_data, labels = [], []

for i, files in enumerate(onlyfiles):
    image_path = data_path + onlyfiles[i]
    images = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    training_data.append(images)
    labels.append(0)

# Criando uma matriz da lista de labels
labels = np.asarray(labels, dtype=np.int32)

# Treinamento do modelo
model = cv2.face.LBPHFaceRecognizer_create()
model.train(training_data, labels)

print("Modelo treinado com sucesso.")

# IMPLEMENTAR
# Defina na chave 0 o nome do candidato

persons = {0: 'Joazinho'}
```

Acabo tomando esse erro:

```
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-506e535e26b8> in <module>
     17 
     18 # Treinamento do modelo
---> 19 model = cv2.face.LBPHFaceRecognizer_create()
     20 model.train(training_data, labels)
     21 

AttributeError: module 'cv2.cv2' has no attribute 'face'
```

Uma solução que encontrei no StackOverflow foi instalar a versão contrib (https://stackoverflow.com/questions/44633378/attributeerror-module-cv2-cv2-has-no-attribute-createlbphfacerecognizer) , mas se faço isso, acaba dando outro erro bizarro: 

`SystemError: Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported!`

Tentei reinstalar todo o env, trocar a versão do Python, mas sem sucesso :( 

O código tá no fork do meu repo.

Minha versão do Python é a 3.6.2 e tentei com a 3.5 e 3.7.1 também
```bash
henrique @ henrique-Inspiron-5448 ~/fiap/trabalhos/tec-processamento-imagens/fiap-ml-tec-proc-imagens-capstone (master)
└─ $ ▶ python --version
Python 3.6.2
```

**Comment by michelpf** [comment]
Henrique, me parece algum problema relacionado a versão do OpenCV.

```
import cv2
print(cv2.__version__)
```
Veja se é a 3.4.2.

Por experiência própria, as vezes quando dá algum erro de incompatibildiade, a melhor forma é remover o pacote e instalar novamente. 

O pacote pode ser instalado por aqui https://anaconda.org/conda-forge/opencv.

Fique atento, se for usar o SIFT e SURF, precisa forçar a versão para 3.4.1.

**Comment by henriquebraga-luizalabs** [comment]
Consegui arrumar atualizando as dependências do Ubuntu e reinstalando o env de novo :pray:
