### ISSUE TITLE
Erro error: /io/opencv/modules/highgui/src/window.cpp:325: error: (-215) size.width>0 && size.height>0 in function imshow

### ISSUE THREAD

**Issue by henriquebraga-luizalabs** [michelpf/fiap-ml-tec-proc-imagens-capstone#4]
Ao executar esse trecho de código: 

```python
contagem_maxima = 100
cam_capture = cv2.VideoCapture("drop.avi")

while True:
    ret, frame = cam_capture.read()
    cv2.imshow("video", frame)
    if frames == 245:
    
        if ret:
        
            contagem += 1
            rosto = face_extractor(frame)
            cv2.imwrite('imagens/foto-{}.jpg'.format(str(contagem)), rosto)
        
        if cv2.waitKey(1) == 13 or contagem == contagem_maxima:
            break
        
cam_capture.release()
cv2.destroyAllWindows()
print("Coleta de amostras completado")
```

Como minha webcam não está funcionando, fiz upload de um vídeo na minha máquina para fazer o treinamento facial.

Porém, ele não está conseguindo ler os frames de vídeos. Fiz um teste tentando um vídeo que baixei na internet chamado "drop.avi" para ver se era algo com o vídeo que gravei, mas o erro persistiu.

Tentei novamente reconfigurar o env, instalar um cara chamado FFMPEG pra poder fazer a leitura de vídeos, mas sem sucesso até agora.

Tá um parto configurar esse ambiente na minha máquina :( 

![setup-opencv](https://user-images.githubusercontent.com/24937898/51358829-217c4480-1aac-11e9-9467-2cc7f8f6ddba.png)

**Comment by henriquebraga-luizalabs** [comment]
Uma solução paleativa que fiz por hora foi treinar o algoritmo com imagens que tirei foto mesmo (sem o vídeo).

**Comment by michelpf** [comment]
Os vídeos AVI são um parto mesmo, por conta do formato da Microsoft. Tente converter para MPEG ou MPG. Existem vários serviços on-line que faz isso para você. Isto deve funcionar.

Sobre sua webcam, ela funciona com outros aplicativos? Não tem muita configuração, deveria funcionar sem problemas.

**Comment by henriquebraga-luizalabs** [comment]
Vou tentar, eu tinha tentando converter pra .mp4 na verdade, mas deu a mesma coisa.

Então, sobre a webcam eu não sei se o problema é físico ou o driver, mas no Linux nunca consegui fazer rolar e quando usava Windows não me lembro se ela funcionava.

**Comment by henriquebraga-luizalabs** [comment]
Mesmo problema com MPEG e MPG :cry: 

![evidencia_mpeg](https://user-images.githubusercontent.com/24937898/51410897-12999e80-1b4d-11e9-8d86-d93d83765619.png)

**Comment by michelpf** [comment]
Minha sugestão é usar o Windows. 
Infelizmente não tenho um ambiente com Ubuntu e nem experiência em como instalar o OpenCV nele 😞 .
Todo o curso foi baseado no Windows, que é o ambiente dos laboratórios.
Em último caso você pode usar os laboratórios da FIAP para concluir o projeto.

**Comment by michelpf** [comment]
Fechando a Issue pois o ambiente do projeto final assim como todo o curso foi baseado em Windows.
