### ISSUE TITLE
Problemas ao usar o comando cv.destroyAllWindows() no MAC

### ISSUE THREAD

**Issue by regisfs** [michelpf/fiap-ml-tec-proc-imagens-capstone#5]
Existe alguma outra forma de utilizar o comando destroyAllWindows() no MAC para que não trave ?

**Comment by michelpf** [comment]
Existe, mas adianto que é um workaround. Isso é um bug conhecido no OpenCV 😢 

```
cv2.imshow("Imagem", image)
cv2.waitKey(0)
cv2.destroyAllWindows()
for i in range (1,5):
    cv2.waitKey(1)
```

Referência: [StackOverflow](https://stackoverflow.com/questions/6116564/destroywindow-does-not-close-window-on-mac-using-python-and-opencv).

**Comment by regisfs** [comment]
Eu havia visto esse workaround no StackOverflow, mas no meu caso ele não funcionou. :'(
