### ISSUE TITLE
Erro ao tentar instalar a biblioteca dlib no Ubuntu

### ISSUE THREAD

**Issue by henriquebraga-luizalabs** [michelpf/fiap-ml-tec-proc-imagens-capstone#6]
Quando tento instalar a biblioteca `dlib` no Ubuntu, ele trava e não sai disso

![screenshot from 2019-01-18 18-37-44](https://user-images.githubusercontent.com/24937898/51411823-6eb1f200-1b50-11e9-9c13-2942c2553715.png)

Eu tentei instalar todos os pacotes no Ubuntu (seguindo esses passos: https://www.learnopencv.com/install-dlib-on-ubuntu/)e recriar o env, mas sem sucesso.

Quase desistindo aqui já de tudo :joy:

**Comment by regisfs** [comment]
Henrique, 

Eu tive um problema parecido e o artigo abaixo me ajudou, veja se ele resolve o seu problema também.

So desconsidera a parte do "brew"

https://medium.com/@arunponnusamy/setting-up-deep-learning-environment-the-easy-way-on-macos-high-sierra-f1b6331ffc40

**Comment by henriquebraga-luizalabs** [comment]
@regisfs  eu uso Ubuntu :( 

Mas consegui resolver instalando umas 500 libs.

@michelpf eu to fazendo os exercícios baseados em imagens ao invés de vídeos porque não consegui resolver o problema da webcam e dos codecs de vídeo.

A base dos algoritmos pelo que vi tá rolando, teria algum problema nisso?

**Comment by michelpf** [comment]
Não tem problema de usar assim, com imagens estáticas.
Infelizmente o curso foi baseado em Windows e Mac, portanto não tenho como ajudar por não pesquisar a fundo a implantação no Ubuntu.

**Comment by michelpf** [comment]
Fechando a Issue considerando que o ambiente para o desenvolvimento do projeto deveria ser Windows. Na impossibilidade de realizar com equipamento próprio é possível utilizar o laboratório da FIAP em horários fora de aula, agendando previamente.
