### ISSUE TITLE
Tamanho do arquivo yolov3.weights

### ISSUE THREAD

**Issue by RonaldoOliveira18** [michelpf/fiap-ml-tec-proc-imagens-capstone#7]
Boa tarde,

Não estou conseguindo realizar o push do pesos/yolov3.weights devido ao tamanho do arquivo.  (242.195 KB). Tem algum problema não realizar o push desse arquivo ou tem alguma outra forma de entregar esse arquivo ?

**Comment by michelpf** [comment]
Não precisa. Na verdade a prática é indicar no README.md do seu projeto que os pesos se encontram em um determinado site, por exemplo neste caso você pode indicar o site da Darknet/Yolo, esse aqui https://pjreddie.com/darknet/yolo/.
